services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: canary_db
      POSTGRES_USER: canary_user
      POSTGRES_PASSWORD: canary_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
